# Generated by Django 5.2.7 on 2026-03-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='special_money',
            field=models.IntegerField(default=0),
        ),
    ]
